#时间
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TestDB
    username: cc
    password: cc123456
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true

#日志
logging:
  file: target/app.log
  level:
    root: WARN
    com.exmaple.cc: TRACE
